# Generated by Django 5.1 on 2024-08-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=300, null=True),
                ),
                ("price", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=20)),
                ("user_pass", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("country", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
                ("city", models.CharField(max_length=60)),
                ("postal_code", models.CharField(max_length=12)),
                ("address", models.TextField(max_length=100)),
                ("address_2", models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
